// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUosvhhKgr898nszki5kH1eiT4P27Ohc8',
    appId: '1:607311678636:web:cd47d9675a2f1fed952309',
    messagingSenderId: '607311678636',
    projectId: 'sudoku-framboos',
    authDomain: 'sudoku-framboos.firebaseapp.com',
    storageBucket: 'sudoku-framboos.appspot.com',
    measurementId: 'G-0TKSH73B0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRpqsfoAr8GgIPkZcRL3WetAE2k5vhIWs',
    appId: '1:607311678636:android:2799877a3341a315952309',
    messagingSenderId: '607311678636',
    projectId: 'sudoku-framboos',
    storageBucket: 'sudoku-framboos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXM8mN0b5wF9cia7XyBF3tBE8uvArvNHQ',
    appId: '1:607311678636:ios:979d1a2032d8202c952309',
    messagingSenderId: '607311678636',
    projectId: 'sudoku-framboos',
    storageBucket: 'sudoku-framboos.appspot.com',
    iosClientId: '607311678636-31p3rnlk9jiv24m33v8r22cngm2jml7m.apps.googleusercontent.com',
    iosBundleId: 'com.framboos.sudoku',
  );
}
